name: Build Frontend

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - uses: actions/checkout@v4 

      - name: Install Node.js
        uses: actions/setup-node@v4 
        with:
          node-version: '20'

      - name: Build React App
        run: |
          cd frontend
          npm install
          npm run build
          rm -rf ../backend/static
          cp -r build ../backend/static

      - name: Commit and Push Build to Backend
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'

          git add backend/static -f
          git commit -m "Move frontend build to backend/static" || echo "No changes to commit"
          git push
